version: '3'

services:
  app:
    build:
      context: .
      dockerfile: docker/dev/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - ./uploads:/app/uploads
    depends_on:
      - redis
    command: go run main.go
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
